name: LibraryOfTruth
favicon: null
layout_spectrum: 0.69287
typography_spectrum: 0.7955949411261827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282826'
    - '#ffffff'
    - '#5e6555'
    - '#ada9a6'
    - '#9c7d44'
  brandStrength: 0.375
  lightness: 0.15513236913830042
  saturation: 0.543351300060749
  rhythmicContrast: 0.6818215935491025
purpose: []
